# fly.toml app configuration file generated for react-router-devtools on 2026-04-05T18:04:39+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'react-router-devtools'
primary_region = 'fra'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'suspend'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
